# Generated by Django 4.2.11 on 2024-04-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=500)),
            ],
        ),
    ]
