# Generated by Django 4.2.11 on 2024-04-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cart_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetails',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
