# Generated by Django 4.2.11 on 2024-04-08 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_checkoutdetails_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.checkoutdetails')),
                ('ud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cart')),
            ],
        ),
    ]
