"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import http
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print('BASE_DIR: ', BASE_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*$%8*a+-ldn=06t+!3%u72djc^z6t!03*e=$9#z!@(d*)7zp)!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    'home',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',                
            ],
        },
    },
]
WSGI_APPLICATION = 'shop.wsgi.application'

SITE_ID=1

ACCOUNT_USERNAME_REQUIRED = False

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


###########MEDIA SETTINGS###############

MEDIA_URL = '/media/'
MEDIA_ROOT =  os.path.join(BASE_DIR, 'media/')
print('MEDIA_ROOT: ', MEDIA_ROOT)

LOGIN_URL = 'home.views.login_usr'
print(LOGIN_URL)



######### Custom User Auth ###########
AUTH_USER_MODEL = "home.CustomUser"

AUTHENTICATION_BACKENDS = ( 
	'django.contrib.auth.backends.ModelBackend', 
	'allauth.account.auth_backends.AuthenticationBackend', 
)


############################################  stripe keys and and payment success////Cancel urls for redirect  ###############################################################3
STRIPE_PUBLISHABLE_KEY = 'pk_test_51P3aPDSCf3PtEQGklCwrMOxVNijr8K6ncqp9aYLqOVAnSnGpx0T83EiLcK6CrY8VKESIY8sMGBPsLwP5KITV1cGt00OckfBarN'
STRIPE_SECRET_KEY = 'sk_test_51P3aPDSCf3PtEQGkJQJ3cpA8tKoFQxRyhNwgyO7IoKPTjYQhaS4uOFmWeB2nycaznIFCJKKqhwQQTPMCGfZgccyZ006MiEhwog'


BACKEND_DOMAIN='http://127.0.0.1:8000'
PAYMENT_SUCCESS_URL='http://127.0.0.1:8000/success/'
PAYMENT_CANCEL_URL='http://127.0.0.1:8000/cancel/'




############################## ALL AUTH SETTINGS ######################################
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'APP': {
            'client_id': '97886935153-odbe7jic5mau74is27vs6lm7qgnbc3nr.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        }
    },
     'facebook': {
        'SCOPE': ['email', 'public_profile'],
        'APP': {
            'client_id': '961443009317778',
            'secret': 'fc4b66d9044849c9a1f9a19b6f8fbeb5',
        }
    }
}
#django-allauth registraion settings
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS =1
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None



# 1 day
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 86400
  
#or any other page
ACCOUNT_LOGOUT_REDIRECT_URL ='/login/'
  
# redirects to profile page if not configured. 
LOGIN_REDIRECT_URL = '/home/'


#################################    email file backend ###################################################3
EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = BASE_DIR / 'emails'


#face book#fc4b66d9044849c9a1f9a19b6f8fbeb5
#961443009317778